apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  # mongo-root-username: cm9vdAo=
  # mongo-root-password: cGFzc3cwcmQK
  # mongo-database-name: YmxvY2tjaGFpbgo=
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  mongo-database-name: cG9k


  # mongo-root-username: dXNlcm5hbWU= echo dXNlcm5hbWU= | base64 --decode = username
  # mongo-root-password: cGFzc3dvcmQ= echo cGFzc3dvcmQ= | base64 --decode = password
  # mongo-database-name: cG9k echo cG9k | base64 --decode = pod