apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  mongo-database-name: cG9k

# https://www.serverlab.ca/tutorials/development/nodejs/containerizing-a-node-js-rest-api-for-kubernetes/
# echo -n 'db-user' | base64
# ZGItdXNlcg==
# echo -n 'super-secret-password' | base64
# c3VwZXItc2VjcmV0LXBhc3N3b3Jk
