# Default values for tutorial-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

volumesAndMounts:
  volumes:
  - name: nodejs-env-file
    configMap:
      name: dd-configmap
  - name: nodejs-env-file2
    configMap:
      name: dd-configmap
  volumesMounts:
    - name: nodejs-env-file
      mountPath: /app/.env
    - name: nodejs-env-file2
      mountPath: /app/.env2
kv:
  KEY1: V1
  KEY2: V2
  KEY3: v3
message: "Welcome to waytoeasylearn"
website: "www.waytoeasylearn.com"
owner:
  name: Vinod Kumar
  place: Hyderabad
  qualification: mca
tags:
  programming: java
  devops: kubernetes
  deployment: helm
  bigdata: hadoop
LangUsed:
  - Java
  - Python
  - Ruby
  - Scala 
label1:
  - fook:
    name: foo
    value: foo1
  - bark:
    name: bar
    value: bar2

secretMaps:
 - name: ME_CONFIG_MONGODB_ADMINUSERNAME
   valueFrom:
      secretKeyRef:
        name: secret
        key: mongo-root-username
 - name: ME_CONFIG_MONGODB_ADMINPASSWORD
   valueFrom:
      secretKeyRef:
        name: secret
        key: mongo-root-password
 - name: ME_CONFIG_MONGODB_DATABASE_NAME
   valueFrom:
      secretKeyRef:
        name: secret
        key: mongo-database-name
 - name: ME_CONFIG_MONGODB_SERVER
   valueFrom:
      configMapKeyRef:
        name: configmap
        key: database_url
 - name: MONGO_URL
   valueFrom:
      configMapKeyRef:
        name: configmap
        key: database_url

envVars:
  var1: 'sdfsdfsdf'
  var2: 'efwefwefwef'

envVarsSecret:
  var3:
      secretKeyRef: my-secret
      key: key

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
